# Generated by Django 4.2.7 on 2025-11-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Evaluation year')),
                ('college', models.CharField(help_text='College name', max_length=100)),
                ('department', models.CharField(help_text='Department name', max_length=100)),
                ('employment_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Employment rate (%)', max_digits=5, null=True)),
                ('full_time_faculty', models.IntegerField(blank=True, help_text='Number of full-time faculty members', null=True)),
                ('visiting_faculty', models.IntegerField(blank=True, help_text='Number of visiting faculty members', null=True)),
                ('tech_transfer_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Technology transfer revenue (hundred million won)', max_digits=12, null=True)),
                ('intl_conference_count', models.IntegerField(blank=True, help_text='Number of international conferences', null=True)),
            ],
            options={
                'db_table': 'department_kpis',
                'ordering': ['-year', 'college', 'department'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_id', models.CharField(db_index=True, help_text='Unique publication ID', max_length=50, unique=True)),
                ('publication_date', models.DateField(help_text='Publication date')),
                ('college', models.CharField(help_text='College name', max_length=100)),
                ('department', models.CharField(help_text='Department name', max_length=100)),
                ('title', models.TextField(help_text='Publication title')),
                ('primary_author', models.CharField(help_text='Primary author name', max_length=100)),
                ('co_authors', models.TextField(blank=True, help_text='Co-authors (semicolon-separated)', null=True)),
                ('journal_name', models.CharField(help_text='Journal name', max_length=255)),
                ('journal_grade', models.CharField(blank=True, help_text='Journal grade/tier', max_length=50, null=True)),
                ('impact_factor', models.DecimalField(blank=True, decimal_places=2, help_text='Impact factor', max_digits=5, null=True)),
                ('is_project_linked', models.BooleanField(default=False, help_text='Whether linked to research project')),
            ],
            options={
                'db_table': 'publications',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='ResearchBudgetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.CharField(db_index=True, help_text='Unique execution ID', max_length=50, unique=True)),
                ('project_number', models.CharField(help_text='Project number', max_length=50)),
                ('project_name', models.CharField(help_text='Project name', max_length=255)),
                ('principal_investigator', models.CharField(help_text='Principal investigator name', max_length=100)),
                ('department', models.CharField(help_text='Department name', max_length=100)),
                ('funding_agency', models.CharField(help_text='Funding agency', max_length=255)),
                ('total_budget', models.BigIntegerField(help_text='Total budget (KRW)')),
                ('execution_date', models.DateField(help_text='Execution date')),
                ('execution_item', models.CharField(help_text='Execution item', max_length=255)),
                ('execution_amount', models.BigIntegerField(help_text='Execution amount (KRW)')),
                ('status', models.CharField(choices=[('집행완료', '집행완료'), ('처리중', '처리중'), ('취소', '취소')], help_text='Execution status', max_length=50)),
                ('note', models.TextField(blank=True, help_text='Additional notes', null=True)),
            ],
            options={
                'db_table': 'research_budget_data',
                'ordering': ['-execution_date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, help_text='Student ID', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Student name', max_length=100)),
                ('college', models.CharField(help_text='College name', max_length=100)),
                ('department', models.CharField(help_text='Department name', max_length=100)),
                ('grade', models.IntegerField(blank=True, help_text='Grade (0 for graduate school)', null=True)),
                ('program_type', models.CharField(choices=[('학사', '학사'), ('석사', '석사'), ('박사', '박사')], help_text='Program type', max_length=50)),
                ('enrollment_status', models.CharField(choices=[('재학', '재학'), ('휴학', '휴학'), ('졸업', '졸업'), ('자퇴', '자퇴'), ('제적', '제적')], help_text='Enrollment status', max_length=50)),
                ('gender', models.CharField(blank=True, help_text='Gender', max_length=10, null=True)),
                ('admission_year', models.IntegerField(help_text='Admission year')),
                ('advisor', models.CharField(blank=True, help_text='Advisor name', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254, null=True)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Original file name', max_length=255)),
                ('file_type', models.CharField(choices=[('department_kpi', 'Department KPI'), ('publication_list', 'Publication List'), ('research_project_data', 'Research Project Data'), ('student_roster', 'Student Roster')], help_text='Type of data file', max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], help_text='Upload processing status', max_length=50)),
                ('records_processed', models.IntegerField(default=0, help_text='Number of records processed')),
                ('error_message', models.TextField(blank=True, help_text='Error message if upload failed', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Upload timestamp')),
            ],
            options={
                'db_table': 'upload_history',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
