# Generated by Django 4.2.7 on 2025-11-03 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhistory',
            name='user',
            field=models.ForeignKey(help_text='User who uploaded the file', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['department'], name='students_departm_33c447_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['enrollment_status'], name='students_enrollm_559cd0_idx'),
        ),
        migrations.AddIndex(
            model_name='researchbudgetdata',
            index=models.Index(fields=['project_number'], name='research_bu_project_5b4320_idx'),
        ),
        migrations.AddIndex(
            model_name='researchbudgetdata',
            index=models.Index(fields=['department'], name='research_bu_departm_c4ec24_idx'),
        ),
        migrations.AddIndex(
            model_name='researchbudgetdata',
            index=models.Index(fields=['execution_date'], name='research_bu_executi_cc2b94_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['publication_date'], name='publication_publica_38baa4_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['journal_grade'], name='publication_journal_5dc8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentkpi',
            index=models.Index(fields=['year'], name='department__year_4bff5e_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentkpi',
            index=models.Index(fields=['department'], name='department__departm_460480_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentkpi',
            unique_together={('year', 'college', 'department')},
        ),
        migrations.AddIndex(
            model_name='uploadhistory',
            index=models.Index(fields=['-uploaded_at'], name='upload_hist_uploade_2de21b_idx'),
        ),
    ]
